[package]
name = "mindmap"
version = "0.1.0"
description = "Mindmap — beautiful, fast mind maps for Windows, Linux and Android"
authors = ["mindmap"]
edition = "2021"

[lib]
name = "mindmap_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
